# 版本一（資產負債表/損益表/現金流量表）

In [3]:
#輸入要的年度與季別

# import package
import requests
import pandas as pd

# 爬取目標網站
year = 107
season = 4
stock_number = 2230

BalanceSheetURL = "https://mops.twse.com.tw/mops/web/ajax_t164sb03";      # 資產負債表
ProfitAndLoseURL = "https://mops.twse.com.tw/mops/web/ajax_t164sb04";    # 損益表
CashFlowStatementURL = "https://mops.twse.com.tw/mops/web/ajax_t164sb05"; # 現金流量表


def crawl_financial_Report(url):
    
    form_data = {
        'encodeURIComponent':1,
        'step':1,
        'firstin':1,
        'off':1,
        'co_id':stock_number,
        'year': year,
        'season': season,
    }

    r = requests.post(url,form_data)
    html_df = pd.read_html(r.text)[1].fillna("")
    return html_df
crawl_financial_Report(BalanceSheetURL)

                    民國107年第4季                                        \
                     單位：新台幣仟元
                         會計項目 107年12月31日          106年12月31日
           Unnamed: 0_level_3         金額      %           金額      %
0                        流動資產
1                     現金及約當現金     172349  17.65       233711  22.79
2          按攤銷後成本衡量之金融資產－流動淨額      79198   8.11            0      0
3                      應收票據淨額       2489   0.25         1177   0.11
4                      應收帳款淨額     150325   15.4       132707  12.94
5                  應收帳款－關係人淨額        947    0.1         1506   0.15
6                     其他應收款淨額      11482   1.18        11494   1.12
7                     本期所得稅資產       1057   0.11         2098    0.2
8                          存貨     191057  19.57       195832  19.09
9                      其他流動資產      26770   2.74        70563   6.88
10                     流動資產合計     635674   65.1       649088  63.28
11                      非流動資產
12                 採用權益法之投資淨額      29417   3.01        27669    2.7
13                  不動產、廠房及設備     263678     27       287347  28.02
14                       無形資產      13607   1.39        13184   1.29
15                    遞延所得稅資產      18899   1.94        16295   1.59
16                    其他非流動資產      15137   1.55        32095   3.13
17                    非流動資產合計     340738   34.9       376590  36.72
18                       資產總額     976412    100  1.02568e+06    100
19                       流動負債
20                       短期借款     191426  19.61       176788  17.24
21        透過損益按公允價值衡量之金融負債－流動          0      0          942   0.09
22                    合約負債－流動       4457   0.46            0      0
23                       應付票據       7018   0.72         8513   0.83
24                       應付帳款      40483   4.15        50180   4.89
25                      其他應付款      36752   3.76        36088   3.52
26                    本期所得稅負債       1432   0.15         1671   0.16
27                     其他流動負債     163145  16.71       216052  21.06
28                     流動負債合計     444713  45.55       490234   47.8
29                      非流動負債
30                       長期借款      23076   2.36        34111   3.33
31                    遞延所得稅負債      10618   1.09         9590   0.93
32                    其他非流動負債      16122   1.65        16696   1.63
33                    非流動負債合計      49816    5.1        60397   5.89
34                       負債總額     494529  50.65       550631  53.68
35                歸屬於母公司業主之權益
36                         股本
37                      普通股股本     396173  40.57       396173  38.63
38                       股本合計     396173  40.57       396173  38.63
39                       資本公積
40                     資本公積合計      50582   5.18        63639    6.2
41                       保留盈餘
42                     法定盈餘公積      29039   2.97        29039   2.83
43                     特別盈餘公積       9374   0.96         9374   0.91
44              未分配盈餘（或待彌補虧損）       9588   0.98       -13057  -1.27
45                     保留盈餘合計      48001   4.92        25356   2.47
46                       其他權益
47                     其他權益合計     -12873  -1.32       -10121  -0.99
48              歸屬於母公司業主之權益合計     481883  49.35       475047  46.32
49                      非控制權益          0      0            0      0
50                       權益總額     481883  49.35       475047  46.32
51                    負債及權益總計     976412    100  1.02568e+06    100
52    預收股款（權益項下）之約當發行股數（單位：股）          0                   0
53  母公司暨子公司所持有之母公司庫藏股股數（單位：股）          0                   0



   Unnamed: 5_level_2 Unnamed: 6_level_2
   Unnamed: 5_level_3 Unnamed: 6_level_3
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53

In [4]:
crawl_financial_Report(ProfitAndLoseURL)

                               民國107年第4季                                \
                                單位：新台幣仟元
                                    會計項目   107年度          106年度
                      Unnamed: 0_level_3      金額      %      金額      %
0                                 營業收入合計  565039    100  551138    100
1                                 營業成本合計  465461  82.38  447312  81.16
2                               營業毛利（毛損）   99578  17.62  103826  18.84
3                             營業毛利（毛損）淨額   99578  17.62  103826  18.84
4                                   營業費用
5                                   推銷費用   31290   5.54   39846   7.23
6                                   管理費用   57295  10.14   52994   9.62
7                                 研究發展費用    2627   0.46    3612   0.66
8                           預期信用減損損失（利益）   -4462  -0.79       0      0
9                                 營業費用合計   86750  15.35   96452   17.5
10                             其他收益及費損淨額
11                             其他收益及費損淨額    -616  -0.11    -255  -0.05
12                              營業利益（損失）   12212   2.16    7119   1.29
13                              營業外收入及支出
14                                  其他收入    5068    0.9    4028   0.73
15                             其他利益及損失淨額    4121   0.73  -19912  -3.61
16                                財務成本淨額    7722   1.37    6171   1.12
17                採用權益法認列之關聯企業及合資損益之份額淨額    1452   0.26      56   0.01
18                            營業外收入及支出合計    2919   0.52  -21999  -3.99
19                              稅前淨利（淨損）   15131   2.68  -14880   -2.7
20                           所得稅費用（利益）合計    5040   0.89    1934   0.35
21                        繼續營業單位本期淨利（淨損）   10091   1.79  -16814  -3.05
22                              本期淨利（淨損）   10091   1.79  -16814  -3.05
23                            其他綜合損益(淨額)
24                           不重分類至損益之項目：
25                           確定福利計畫之再衡量數   -1017  -0.18   -1211  -0.22
26  採用權益法認列之關聯企業及合資之其他綜合損益之份額-不重分類至損益之項目     311   0.06       0      0
27                        與不重分類之項目相關之所得稅    -203  -0.04    -206  -0.04
28                        後續可能重分類至損益之項目：
29                     國外營運機構財務報表換算之兌換差額   -3621  -0.64   -8735  -1.58
30  採用權益法認列關聯企業及合資之其他綜合損益之份額-可能重分類至損益之項目      -9      0       2      0
31                       與可能重分類之項目相關之所得稅    -878  -0.16   -1055  -0.19
32                            其他綜合損益（淨額）   -3255  -0.58   -8683  -1.58
33                              本期綜合損益總額    6836   1.21  -25497  -4.63
34                             淨利（損）歸屬於：
35                           母公司業主（淨利∕損）   10091   1.79  -17623   -3.2
36                           非控制權益（淨利∕損）       0      0     809   0.15
37                           母公司業主（綜合損益）    6836   1.21  -23782  -4.32
38                           非控制權益（綜合損益）       0      0   -1715  -0.31
39                                基本每股盈餘
40                                基本每股盈餘    0.25          -0.44
41                                稀釋每股盈餘
42                                稀釋每股盈餘    0.25          -0.44



   Unnamed: 5_level_2
   Unnamed: 5_level_3
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42

In [5]:
crawl_financial_Report(CashFlowStatementURL)

            民國107年第4季                                                        \
             單位：新台幣仟元
                 會計項目   107年度   106年度 Unnamed: 3_level_2 Unnamed: 4_level_2
   Unnamed: 0_level_3      金額      金額 Unnamed: 3_level_3 Unnamed: 4_level_3
0       營業活動之現金流量－間接法
1      繼續營業單位稅前淨利（淨損）   15131  -14880
2          本期稅前淨利（淨損）   15131  -14880
3                折舊費用   32779   24157
4                攤銷費用     151     151
..                ...     ...     ...                ...                ...
56    匯率變動對現金及約當現金之影響   -1761   -8000
57   本期現金及約當現金增加（減少）數  -61362  -47457
58        期初現金及約當現金餘額  233711  281168
59        期末現金及約當現金餘額  172349  233711
60    資產負債表帳列之現金及約當現金  172349  233711



   Unnamed: 5_level_2 Unnamed: 6_level_2
   Unnamed: 5_level_3 Unnamed: 6_level_3
0
1
2
3
4
..                ...                ...
56
57
58
59
60

[61 rows x 7 columns]

# 版本二

# 現金流量表

In [156]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zc3/zc3_'+stocknumber+'.djhtm')
df = df[2][0:]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
0,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
1,種類,合併,合併,合併,合併,合併,合併,合併,合併
2,稅前淨利－CFO,132147,128782,112336,80545,68182,111082,98897,87588
3,折舊－CFO,67084,66137,65377,73705,76192,74806,72505,70351
4,攤提－CFO,1471,1394,1379,1344,1355,1224,1105,1057
...,...,...,...,...,...,...,...,...,...
92,籌資活動之現金流量,-40757,-17183,-229112,-931,-22413,14283,-172435,-29346
93,匯率影響數,2099,-11197,-1618,1914,1787,2687,-1672,14095
94,本期產生現金流量,-24622,2969,-197267,4027,67856,89082,-143498,54447
95,期初現金及約當現金,455399,452430,649697,645671,577815,488732,632230,577783
96,期末現金及約當現金,430777,455399,452430,649697,645671,577815,488732,632230

In [158]:
df_T = df.T
df_T

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
0,期別,種類,稅前淨利－CFO,折舊－CFO,攤提－CFO,預期信用減損損失（利益）－CFO,透過損益按公允價值衡量金融資產及負債之淨損失（利益）－,除列按攤銷後成本衡量金融資產淨損失（利益）－CFO,金融資產重分類淨損失（利益）－CFO,存貨跌價損失增加（減少）－CFO,...,取得子公司股權－CFF,處分子公司股權－CFF,支付利息－CFF,退還（支付）所得稅－CFF,調整項（出貨）－CFF,籌資活動之現金流量,匯率影響數,本期產生現金流量,期初現金及約當現金,期末現金及約當現金
1,2020.1Q,合併,132147,67084,1471,2,3,0,0,0,...,0,0,-977,0,-670,-40757,2099,-24622,455399,430777
2,2019.4Q,合併,128782,66137,1394,-1,-2,0,0,0,...,0,0,-539,0,-460,-17183,-11197,2969,452430,455399
3,2019.3Q,合併,112336,65377,1379,4,68,0,0,0,...,0,0,-1433,0,-986,-229112,-1618,-197267,649697,452430
4,2019.2Q,合併,80545,73705,1344,4,552,0,0,0,...,0,0,-437,0,-1558,-931,1914,4027,645671,649697
5,2019.1Q,合併,68182,76192,1355,-5,338,0,0,0,...,0,0,-1189,0,-562,-22413,1787,67856,577815,645671
6,2018.4Q,合併,111082,74806,1224,-0,113,0,0,0,...,0,0,-437,0,425,14283,2687,89082,488732,577815
7,2018.3Q,合併,98897,72505,1105,-1,184,0,0,0,...,0,0,-1253,0,467,-172435,-1672,-143498,632230,488732
8,2018.2Q,合併,87588,70351,1057,-1,32,0,0,0,...,0,0,-545,0,-1107,-29346,14095,54447,577783,632230

In [159]:
x = df_T.values.tolist()[0]
x

['期別',
 '種類',
 '稅前淨利－CFO',
 '折舊－CFO',
 '攤提－CFO',
 '預期信用減損損失（利益）－CFO',
 '透過損益按公允價值衡量金融資產及負債之淨損失（利益）－',
 '除列按攤銷後成本衡量金融資產淨損失（利益）－CFO',
 '金融資產重分類淨損失（利益）－CFO',
 '存貨跌價損失增加（減少）－CFO',
 '利息支出－CFO',
 '存貨盤（盈）虧及報廢－CFO',
 '利息收入－CFO',
 '股利收入－CFO',
 '股份基礎給付酬勞成本－CFO',
 '採用權益法認列之關聯企業及合資利益份額－CFO',
 '採用權益法認列之關聯企業及合資損失份額－CFO',
 '處分不動產、廠房及設備收益－CFO',
 '處分不動產、廠房及設備損失－CFO',
 '處分投資性不動產損失（利益）－CFO',
 '處分無形資產損失（利益）－CFO',
 '處分投資損失－CFO',
 '處分投資利益－CFO',
 '金融商品減損損失－CFO',
 '金融商品減損迴轉利益－CFO',
 '資產減損損失－CFO',
 '資產減損迴轉利益－CFO',
 '買回公司債損失（利益）－CFO',
 '提列各項準備－CFO',
 '回轉各項準備－CFO',
 '透過損益按公允價值衡量之金融資產（增加）減少－CFO',
 '避險之金融資產（增加）減少－CFO',
 '合約資產（增加）減少－CFO',
 '應收帳款（增加）減少－CFO',
 '其他應收帳款（增加）減少－CFO',
 '存貨（增加）減少－CFO',
 '預付款（增加）減少－CFO',
 '生物性資產（增加）減少－CFO',
 '其他金融資產（增加）減少－CFO',
 '透過損益按公允價值衡量金融負債增加（減少）－CFO',
 '避險之金融負債增加（減少）－CFO',
 '合約負債增加（減少）－CFO',
 '應付帳款增加（減少）－CFO',
 '其他應付款增加（減少）－CFO',
 '其他金融負債增加（減少）－CFO',
 '負債準備增加（減少）CFO－CFO',
 '提列員工退休金準備－CFO',
 '支付員工退休金－CFO',
 '利息收現－CFO',
 '收取股利－CFO',
 '支付利息－CFO',
 '支付股利－CFO',
 '退還（支付）所得稅－CFO',
 '調整項（出貨）－CFO',
 '來自營運之現金流量',
 '應收款項增加（減少）－CFI',
 '新增投資－CFI',
 '出售投資－CFI',
 '購置不動產廠房設備（含預付）－CFI',
 '處分不動產廠房設備（含預付）－CFI',
 '投資性不動產出售（購買）－CFI',
 '無形資產（增加）減少－CFI',
 '其他金融資產（增加）減少－CFI',
 '購併他公司支付現金淨額－CFI',
 '取得購併公司現金－CFI',
 '處分子公司現金流出－CFF',
 '收到利息－CFI',
 '收到股利－CFI',
 '退還（支付）所得稅－CFI',
 '調整項（出貨）－CFI',
 '投資活動之現金流量',
 '短期借款增加（減少）－CFF',
 '應付短期票券增加（減少）－CFF',
 '發行公司債－CFF',
 '償還公司債－CFF',
 '舉借長期借款－CFF',
 '償還長期借款－CFF',
 '發行特別股負債－CFF',
 '償還長特別股負債－CFF',
 '庫藏股票減少（增加）－CFF',
 '現金增（減）資－CFF',
 '行使員工認股權－CFF',
 '支付現金股利－CFF',
 '透過損益按公允價值衡量之金融負債增加（減少）－CFF',
 '按攤銷後成本衡量之金融負債增加（減少）－CFF',
 '其他金融負債增加（減少）－CFF',
 '非控制權益增加（減少）－CFF',
 '取得子公司股權－CFF',
 '處分子公司股權－CFF',
 '支付利息－CFF',
 '退還（支付）所得稅－CFF',
 '調整項（出貨）－CFF',
 '籌資活動之現金流量',
 '匯率影響數',
 '本期產生現金流量',
 '期初現金及約當現金',
 '期末現金及約當現金']

# 資產負債表

In [160]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcp/zcpa/zcpa_'+stocknumber+'.djhtm')
df = df[2][0:]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
0,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
1,種類,合併,合併,合併,合併,合併,合併,合併,合併
2,現金及約當現金,430777,455399,452430,649697,645671,577815,488732,632230
3,透過損益按公允價值衡量之金融資產－流動,1254,327,322,1323,3084,3505,4057,1205
4,透過其他綜合損益按公允價值衡量之金融資產－流動,129219,127397,132133,113594,107313,99562,99214,102028
...,...,...,...,...,...,...,...,...,...
89,共同控制下前手權益,0,0,0,0,0,0,0,0
90,合併前非屬共同控制股權,0,0,0,0,0,0,0,0
91,非控制權益,763,685,641,607,672,679,658,634
92,股東權益總額,1677029,1622095,1587497,1554422,1743518,1677496,1575830,1490635
93,負債及股東權益總額,2343296,2264805,2134234,2239344,2187437,2090128,1969889,2053413

In [161]:
df_T = df.T
df_T

,0,1,2,3,4,5,6,7,8,9,...,84,85,86,87,88,89,90,91,92,93
0,期別,種類,現金及約當現金,透過損益按公允價值衡量之金融資產－流動,透過其他綜合損益按公允價值衡量之金融資產－流動,按攤銷後成本衡量之金融資產－流動,避險之金融資產－流動,合約資產－流動,應收帳款及票據,其他應收款,...,未分配盈餘,保留盈餘,其他權益,庫藏股票帳面值,母公司股東權益合計,共同控制下前手權益,合併前非屬共同控制股權,非控制權益,股東權益總額,負債及股東權益總額
1,2020.1Q,合併,430777,1254,129219,302,0,0,146421,60,...,1046781,1385496,-24873,0,1676266,0,0,763,1677029,2343296
2,2019.4Q,合併,455399,327,127397,300,26,0,139771,52,...,1011513,1333335,-27568,0,1621410,0,0,685,1622095,2264805
3,2019.3Q,合併,452430,322,132133,0,37,0,145422,57,...,963374,1281906,-10675,0,1586856,0,0,641,1587497,2134234
4,2019.2Q,合併,649697,1323,113594,0,1,0,116131,1542,...,923705,1245576,-7386,0,1553815,0,0,607,1554422,2239344
5,2019.1Q,合併,645671,3084,107313,4179,1,0,106741,49,...,1135005,1437946,-10725,0,1742846,0,0,672,1743518,2187437
6,2018.4Q,合併,577815,3505,99562,14278,23,0,129198,65,...,1073707,1376648,-15450,0,1676818,0,0,679,1677496,2090128
7,2018.3Q,合併,488732,4057,99214,11892,124,0,129540,64,...,974796,1277738,-18181,0,1575172,0,0,658,1575830,1969889
8,2018.2Q,合併,632230,1205,102028,13427,32,0,88196,3186,...,886529,1189471,-15080,0,1490002,0,0,634,1490635,2053413

In [162]:
x = df_T.values.tolist()[0]
x

['期別',
 '種類',
 '現金及約當現金',
 '透過損益按公允價值衡量之金融資產－流動',
 '透過其他綜合損益按公允價值衡量之金融資產－流動',
 '按攤銷後成本衡量之金融資產－流動',
 '避險之金融資產－流動',
 '合約資產－流動',
 '應收帳款及票據',
 '其他應收款',
 '資金貸予他人－流動',
 '存貨',
 '生物資產流動',
 '預付費用及預付款',
 '應收代理店款',
 '待出售非流動資產',
 '當期所得稅資產－流動',
 '其他金融資產－流動',
 '其他流動資產',
 '流動資產',
 '透過損益按公允價值衡量之金融資產－非流動',
 '透過其他綜合損益按公允價值衡量之金融資產－非流動',
 '按攤銷後成本衡量之金融資產－非流動',
 '避險之金融資產－非流動',
 '合約資產－非流動',
 '採權益法之長期股權投資',
 '預付投資款',
 '不動產廠房及設備',
 '商譽淨額',
 '特許權',
 '發展中之無形資產',
 '其他無形資產淨額',
 '商譽及無形資產合計',
 '遞延資產合計',
 '遞延借項－非流動',
 '投資性不動產淨額',
 '預付設備款',
 '長期預付租金',
 '生物資產非流動',
 '其他非流動資產－其他',
 '其他非流動資產',
 '非流動資產',
 '資產總額',
 '短期借款',
 '應付商業本票／承兌匯票',
 '透過損益按公允價值衡量之金融負債－流動',
 '避險之金融負債－流動',
 '按攤銷後成本衡量之金融負債－流動',
 '合約負債－流動',
 '應付帳款及票據',
 '其他應付款',
 '當期所得稅負債',
 '負債準備－流動',
 '與待出售非流動資產直接相關之負債',
 '其他金融負債－流動',
 '一年內到期長期負債',
 '特別股負債－流動',
 '應付代理店款',
 '其他流動負債',
 '流動負債',
 '透過損益按公允價值衡量之金融負債－非流動',
 '避險之金融負債－非流動',
 '按攤銷後成本衡量之金融負債－非流動',
 '合約負債－非流動',
 '特別股負債－非流動',
 '應付公司債－非流動',
 '銀行借款－非流動',
 '其他長期借款－非流動',
 '負債準備－非流動',
 '遞延貸項',
 '應計退休金負債',
 '遞延所得稅',
 '其他非流動負債',
 '非流動負債',
 '負債總額',
 '普通股股本',
 '特別股股本',
 '預收股款',
 '待分配股票股利',
 '換股權利證書',
 '股本',
 '資本公積合計',
 '法定盈餘公積',
 '特別盈餘公積',
 '未分配盈餘',
 '保留盈餘',
 '其他權益',
 '庫藏股票帳面值',
 '母公司股東權益合計',
 '共同控制下前手權益',
 '合併前非屬共同控制股權',
 '非控制權益',
 '股東權益總額',
 '負債及股東權益總額']

# 綜合損益表

In [163]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcq/zcq_'+stocknumber+'.djhtm')
df = df[2][0:]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
0,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
1,種類,合併,合併,合併,合併,合併,合併,合併,合併
2,營業收入毛額,310597,317237,293045,240998,218704,289770,260348,233277
3,營業收入淨額,310597,317237,293045,240998,218704,289770,260348,233277
4,銷貨成本,149813,157996,153613,137325,128352,151728,136967,121689
...,...,...,...,...,...,...,...,...,...
102,庫藏股數－母公司,0,0,0,0,0,0,0,0
103,庫藏股數－子公司持有母公司股票或其他,0,0,0,0,0,0,0,0
104,庫藏股數（母持及子持母）,0,0,0,0,0,0,0,0
105,稅前息前淨利,132678,129426,113180,81410,69081,111958,99636,88216
106,稅前息前折舊前淨利,201232,196957,179936,156459,146629,187988,173246,159625

In [164]:
df_T = df.T
df_T #上一個表格的欄位互換

,0,1,2,3,4,5,6,7,8,9,...,97,98,99,100,101,102,103,104,105,106
0,期別,種類,營業收入毛額,營業收入淨額,銷貨成本,營業成本,營業毛利,聯屬公司已（未）實現銷貨利益,已實現銷貨毛利,營業費用,...,綜合損益歸屬共同控制下前手權益,每股盈餘,加權平均股數,發放特別股股息,常續性稅後淨利,庫藏股數－母公司,庫藏股數－子公司持有母公司股票或其他,庫藏股數（母持及子持母）,稅前息前淨利,稅前息前折舊前淨利
1,2020.1Q,合併,310597,310597,149813,149813,160784,-8,160777,32323,...,0,4.51,25930,0,116974,0,0,0,132678,201232
2,2019.4Q,合併,317237,317237,157996,157996,159241,-39,159202,34943,...,0,4.47,25930,0,117108,0,0,0,129426,196957
3,2019.3Q,合併,293045,293045,153613,153613,139432,-20,139412,31379,...,0,3.90,25930,0,101717,0,0,0,113180,179936
4,2019.2Q,合併,240998,240998,137325,137325,103673,57,103730,27165,...,0,2.57,25930,0,66408,0,0,0,81410,156459
5,2019.1Q,合併,218704,218704,128352,128352,90352,5,90358,26018,...,0,2.37,25930,0,61926,0,0,0,69081,146629
6,2018.4Q,合併,289770,289770,151728,151728,138042,77,138119,30852,...,0,3.86,25930,0,100588,0,0,0,111958,187988
7,2018.3Q,合併,260348,260348,136967,136967,123381,-14,123367,28128,...,0,3.44,25930,0,90013,0,0,0,99636,173246
8,2018.2Q,合併,233277,233277,121689,121689,111588,-57,111531,26440,...,0,2.79,25930,0,74940,0,0,0,88216,159625

In [165]:
x = df_T.values.tolist()[0]
x

['期別',
 '種類',
 '營業收入毛額',
 '營業收入淨額',
 '銷貨成本',
 '營業成本',
 '營業毛利',
 '聯屬公司已（未）實現銷貨利益',
 '已實現銷貨毛利',
 '營業費用',
 '推銷費用',
 '管理費用',
 '研究發展費',
 '其他費用',
 '預期信用減損（損失）利益－營業費用',
 '其他收益及費損淨額',
 '營業利益',
 '利息收入',
 '租金收入',
 '權利金收入',
 '股利收入',
 '廉價購買收益',
 '違約金收入',
 '預期信用減損利益',
 '沖銷逾期應付帳款利益',
 '補助收益',
 '其他收入－其他',
 '其他收入',
 '處分不動產、廠房及設備利益',
 '處分投資利益',
 '外幣兌換利益',
 '透過損益按公允價值衡量之金融資產（負債）利益',
 '按攤銷後成本衡量之金融負債利益',
 '避險工具之利益',
 '資產評價利益',
 '金融資產減損迴轉利益',
 '資產減損迴轉利益',
 '賠償收入',
 '買回公司債利益',
 '停工損失',
 '合約損失',
 '賠償損失',
 '處分不動產、廠房及設備損失',
 '處分投資損失',
 '外幣兌換損失',
 '透過損益按公允價值衡量之金融資產（負債）損失',
 '按攤銷後成本衡量之金融負債損失',
 '避險工具之損失',
 '資產評價損失',
 '金融資產減損損失',
 '資產減損損失',
 '買回公司債損失',
 '其他利益及損失－其他',
 '其他利益及損失',
 '利息支出',
 '負債性特別股股息',
 '財務成本－其他',
 '財務成本',
 '採權益法之關聯企業及合資損益之份額',
 '預期信用減損（損失）利益',
 '除列按攤銷後成本衡量金融資產淨損益',
 '金融資產重分類淨損益',
 '營業外收入及支出－其他',
 '營業外收入及支出',
 '稅前淨利',
 '所得稅費用',
 '繼續營業單位損益',
 '停業單位損益',
 '合併前非屬共同控制股權損益',
 '其他損益調整項－非常項目及累計影響數',
 '合併總損益',
 '確定福利計畫之再衡量數－不重分類－OCI',
 '不動產重估價之利益（損失）－不重分類－OCI',
 '指定按公允價值衡量金融負債信用風險變動影響－不重分－',
 '待售待分業主非流資（處分群組）直接相關權益－不重分－',
 '透過FVOCI衡量權益工具投資未實現評價損益－不重分',
 '避險工具之損益－不重分類－OCI',
 '採權益法認列關聯企業及合資其他綜合損益份額－不重分－',
 '其他綜合損益－其他－不重分類－OCI',
 '與其他綜合損益組成部分相關之所得稅－不重分類－OCI',
 '不重分類至損益之項目－OCI',
 '國外營運機構財務報表換算之兌換差額－可重分類－OCI',
 '待售待分業主非流資（處分群組）直接相關權益－可重分－',
 '透FVOCI衡量債務工具投資未實現評價損益－可重分類',
 '避險工具之損益－可重分類－OCI',
 '採權益法認列關聯企業及合資其他綜合損益份額－可重分－',
 '其他綜合損益－其他－可重分類－OCI',
 '與其他綜合損益組成部分相關之所得稅－可重分類－OCI',
 '後續可能重分類至損益之項目－OCI',
 '合併前非屬共同控制股權綜合損益淨額－OCI',
 '其他綜合損益－OCI',
 '本期綜合損益總額',
 '歸屬母公司淨利（損）',
 '歸屬非控制權益淨利（損）',
 '歸屬共同控制下前手權益淨利（損）',
 '綜合損益歸屬母公司',
 '綜合損益歸屬非控制權益',
 '綜合損益歸屬共同控制下前手權益',
 '每股盈餘',
 '加權平均股數',
 '發放特別股股息',
 '常續性稅後淨利',
 '庫藏股數－母公司',
 '庫藏股數－子公司持有母公司股票或其他',
 '庫藏股數（母持及子持母）',
 '稅前息前淨利',
 '稅前息前折舊前淨利']

# 個股股本形成

In [93]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcb/zcb_'+stocknumber+'.djhtm')
df = df[2][1:]
df = df[0:29]
#df.columns = df.iloc[0]
df

      0          1       2            3       4           5       6
1    年度       現金增資      比重        盈餘轉增資      比重       公積及其他      比重
2   109  72.096468   2.78%  2288.442323  88.25%  232.499258   8.97%
3   108  72.096468   2.78%  2288.442323  88.25%  232.499258   8.97%
4   107  72.096468   2.78%  2288.442323  88.25%  232.499258   8.97%
5   106  72.096468   2.78%  2288.442323  88.25%  232.499258   8.97%
6   105  72.096468   2.78%  2288.442323  88.25%  232.499258   8.97%
7   104  72.096468   2.78%  2288.442323  88.25%  232.499258   8.97%
8   103  72.096438   2.78%  2288.442323  88.26%  232.427478   8.96%
9   102  72.096418   2.78%  2288.442323  88.26%  232.322968   8.96%
10  101  72.096388   2.78%  2288.442323  88.27%  231.904858   8.95%
11  100  72.096328   2.78%  2288.442323  88.30%  231.083608   8.92%
12   99  72.196278   2.79%  2288.442323  88.32%  230.369268   8.89%
13   98  72.196208   2.79%  2288.442323  88.35%  229.632128   8.87%
14   97  72.196138   2.82%  2269.130243  88.55%  221.217348   8.63%
15   96  75.989115   2.88%  2342.431299  88.64%  224.289956   8.49%
16   95  75.989065   2.94%  2291.537379  88.72%  215.442336   8.34%
17   94  75.989035   3.07%  2220.121049  89.77%  176.892376   7.15%
18   93  75.988995   3.27%  2072.998659  89.15%  176.208716   7.58%
19   92   76.39659   3.77%   1773.12014  87.49%   177.14517   8.74%
20   91   76.39658   4.10%   1608.74692  86.39%   177.14517   9.51%
21   90   76.39659   4.54%   1429.71355  84.94%   177.14517  10.52%
22   89   76.39658   6.54%    915.39471  78.31%   177.14517  15.15%
23   88   64.89657   8.46%     702.1916  91.54%           0   0.00%
24   87   52.65671   8.71%    552.06089  91.29%           0   0.00%
25   86   52.65671  12.90%    355.47329  87.10%           0   0.00%
26   85   52.65671  19.84%    212.76329  80.16%           0   0.00%
27   84   52.65671  36.59%     91.24329  63.41%           0   0.00%
28   83   52.65671  67.51%     25.34329  32.49%           0   0.00%
29   82   52.65671  86.56%      8.17369  13.44%           0   0.00%

# 經營績效

In [94]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcd/zcd_'+stocknumber+'.djhtm')
df = df[2][1:]
#df.columns = df.iloc[0]
df

         0         1       2       3       4        5          6          7
1       季別    加權平均股數    營業收入    稅前淨利    稅後淨利  每股營收(元)  稅前每股盈餘(元)  稅後每股盈餘(元)
2   109.1Q  25930380  310597  132147  116987    11.98       5.10       4.51
3   108.4Q  25930380  317237  128782  116035    12.23       4.97       4.47
4   108.3Q  25930380  293045  112336  101070    11.30       4.33       3.90
5   108.2Q  25930380  240998   80545   66765     9.29       3.11       2.57
6   108.1Q  25930380  218704   68182   61394     8.43       2.63       2.37
7   107.4Q  25930380  289770  111082   99984    11.17       4.28       3.86
8   107.3Q  25930380  260348   98897   89072    10.04       3.81       3.44
9   107.2Q  25930380  233277   87588   72291     9.00       3.38       2.79
10  107.1Q  25930380  248079   99944   89785     9.57       3.85       3.46
11  106.4Q  25930380  277570  111675   99286    10.70       4.31       3.83
12  106.3Q  25930380  252107  100518   89925     9.72       3.88       3.47
13  106.2Q  25930380  213855   86117   66271     8.25       3.32       2.56
14  106.1Q  25930380  233914   97823   87629     9.02       3.77       3.38
15  105.4Q  25930380  262227  112047  100200    10.11       4.32       3.86
16  105.3Q  25930380  260406  108250   96759    10.04       4.17       3.73
17  105.2Q  25930380  221810   93406   72506     8.55       3.60       2.80
18  105.1Q  25930380  203495   72256   64781     7.85       2.79       2.50
19  104.4Q  25930288  203519   80644   72837     7.85       3.11       2.81
20  104.3Q  25930380  212505   83395   75329     8.20       3.22       2.91
21  104.2Q  25930375  205440   98132   79418     7.92       3.78       3.06

# 個股獲利能力

In [96]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zce/zce_'+stocknumber+'.djhtm')
df = df[2][2:]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8,9
2,季別,營業收入,營業成本,營業毛利,毛利率,營業利益,營益率,業外收支,稅前淨利,稅後淨利
3,109.1Q,310597,149813,160784,51.77%,128522,41.38%,3626,132147,116987
4,108.4Q,317237,157996,159241,50.20%,124244,39.16%,4538,128782,116035
5,108.3Q,293045,153613,139432,47.58%,107887,36.82%,4449,112336,101070
6,108.2Q,240998,137325,103673,43.02%,76304,31.66%,4241,80545,66765
7,108.1Q,218704,128352,90352,41.31%,64266,29.38%,3916,68182,61394
8,107.4Q,289770,151728,138042,47.64%,107123,36.97%,3959,111082,99984
9,107.3Q,260348,136967,123381,47.39%,95245,36.58%,3652,98897,89072
10,107.2Q,233277,121689,111588,47.84%,84428,36.19%,3159,87588,72291
11,107.1Q,248079,123104,124975,50.38%,96827,39.03%,3117,99944,89785
12,106.4Q,277570,138855,138715,49.97%,108895,39.23%,2780,111675,99286
13,106.3Q,252107,126231,125877,49.93%,98056,38.89%,2462,100518,89925
14,106.2Q,213855,105102,108753,50.85%,83255,38.93%,2862,86117,66271
15,106.1Q,233914,112429,121486,51.94%,95352,40.76%,2470,97822,87629
16,105.4Q,262227,125117,137110,52.29%,109907,41.91%,2140,112047,100200
17,105.3Q,260406,128367,132039,50.71%,106262,40.81%,1987,108250,96759
18,105.2Q,221810,107469,114341,51.55%,91321,41.17%,2085,93406,72506
19,105.1Q,203495,112125,91370,44.90%,70467,34.63%,1789,72256,64781
20,104.4Q,203519,104608,98911,48.60%,77964,38.31%,2680,80644,72837
21,104.3Q,212505,110188,102316,48.15%,78389,36.89%,5006,83395,75329
22,104.2Q,205440,105736,99704,48.53%,77069,37.51%,21063,98132,79418
23,104.1Q,222034,112585,109449,49.29%,86626,39.01%,1633,88259,78990
24,103.4Q,222521,111976,110545,49.68%,88216,39.64%,1095,89311,79985
25,103.3Q,209050,103471,105578,50.50%,84427,40.39%,949,85377,76331
26,103.2Q,183020,91826,91194,49.83%,70709,38.63%,3384,74094,59698
27,103.1Q,148215,77839,70376,47.48%,52518,35.43%,780,53297,47867
28,102.4Q,145806,80965,64841,44.47%,47754,32.75%,2618,50373,44810
29,102.3Q,162577,83636,78941,48.56%,59618,36.67%,-268,59350,51952
30,102.2Q,155886,79468,76419,49.02%,57629,36.97%,2388,60017,51808
31,102.1Q,132755,71989,60766,45.77%,44428,33.47%,1320,45748,39577
32,101.4Q,131445,69449,61996,47.16%,46389,35.29%,-105,46284,41604
33,101.3Q,141499,72345,69155,48.87%,52798,37.31%,964,53762,49380
34,101.2Q,128186,65579,62607,48.84%,46872,36.57%,-915,45957,41843
35,101.1Q,105615,55210,50404,47.72%,35117,33.25%,556,35673,33492
36,100.4Q,104711,57865,46846,44.74%,32930,31.45%,691,33621,31579
37,100.3Q,106484,61713,44771,42.04%,31598,29.67%,562,32160,30395
38,100.2Q,110508,59652,50856,46.02%,37866,34.27%,1188,39055,35950
39,100.1Q,105377,53707,51671,49.03%,39163,37.16%,1149,40312,36278
40,99.4Q,110142,55325,54817,49.77%,41513,37.69%,1369,42882,40720
41,99.3Q,112247,56122,56125,50.00%,43066,38.37%,6610,49675,46940
42,99.2Q,104962,53036,51926,49.47%,40469,38.56%,1941,42410,40282
43,99.1Q,92187,48001,44185,47.93%,34128,37.02%,1175,35303,33663
44,98.4Q,92094,47400,44695,48.53%,33642,36.53%,1726,35368,32666
45,98.3Q,89936,47078,42858,47.65%,31984,35.56%,973,32957,30551
46,98.2Q,74212,39916,34296,46.21%,25127,33.86%,1262,26389,24442
47,98.1Q,39500,32020,7480,18.94%,1209,3.06%,-461,748,1559
48,97.4Q,64562,44367,20195,31.28%,12022,18.62%,1072,13094,12446
49,97.3Q,92979,49885,43094,46.35%,32917,35.40%,1513,34430,30574
50,97.2Q,88137,47915,40221,45.64%,30373,34.46%,2004,32377,28771
51,97.1Q,87480,49241,38239,43.71%,29123,33.29%,2449,31572,28143
52,96.4Q,93860,49024,44836,47.77%,36758,39.16%,NaN,39332,34485
53,96.3Q,88955,48231,40724,45.78%,32353,36.37%,NaN,34218,30370
54,96.2Q,74918,42738,32180,42.95%,24734,33.01%,NaN,28024,25484
55,96.1Q,64897,40287,24610,37.92%,17877,27.55%,NaN,20068,18839
56,95.4Q,74963,40510,34453,45.96%,27408,36.56%,NaN,29508,27912
57,95.3Q,82476,41344,41132,49.87%,33632,40.78%,NaN,34663,32489
58,95.2Q,82118,39619,42498,51.75%,35323,43.01%,NaN,36272,34002
59,95.1Q,77850,40124,37727,48.46%,30902,39.69%,NaN,32919,32607
60,94.4Q,79228,37914,41314,52.15%,34410,43.43%,NaN,35588,33900
61,94.3Q,70501,39544,30957,43.91%,24177,34.29%,NaN,24467,24488

# 個股合併月營收

In [100]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zch/zch_'+stocknumber+'.djhtm')
df = df[2][2:]
df = df[3:]
#df.columns = df.iloc[0]
df

         0          1        2          3        4           5        6    7
5      年/月         營收      月增率       去年同期      年增率        累計營收      年增率  NaN
6   109/04   96001572  -15.43%   74693615   28.53%   406598755   38.58%  NaN
7   109/03  113519599   21.55%   79721587   42.40%   310597183   42.02%  NaN
8   109/02   93394449   -9.92%   60889055   53.38%   197077584   41.80%  NaN
9   109/01  103683135    0.36%   78093827   32.77%   103683135   32.77%  NaN
10  108/12  103313138   -4.24%   89830598   15.01%  1069985448    3.73%  NaN
11  108/11  107884396    1.74%   98389414    9.65%   966672310    2.66%  NaN
12  108/10  106039531    3.79%  101550181    4.42%   858787914    1.84%  NaN
13  108/09  102170096   -3.72%   94921920    7.64%   752748383    1.49%  NaN
14  108/08  106117619   25.20%   91055038   16.54%   650578287    0.59%  NaN
15  108/07   84757724   -1.29%   74370924   13.97%   544460668   -2.03%  NaN
16  108/06   85867929    6.75%   70438298   21.91%   459702944   -4.50%  NaN
17  108/05   80436931    7.69%   80968732   -0.66%   373835015   -9.02%  NaN
18  108/04   74693615   -6.31%   81869781   -8.77%   293398084  -11.08%  NaN
19  108/03   79721587   30.93%  103697437  -23.12%   218704469  -11.84%  NaN
20  108/02   60889055  -22.03%   64640562   -5.80%   138982882   -3.74%  NaN
21  108/01   78093827  -13.07%   79740672   -2.07%    78093827   -2.07%  NaN
22  107/12   89830598   -8.70%   89897252   -0.07%  1031473557    5.53%  NaN
23  107/11   98389414   -3.11%   93153310    5.62%   941642959    6.09%  NaN
24  107/10  101550181    6.98%   94519722    7.44%   843253545    6.15%  NaN
25  107/09   94921920    4.25%   88578988    7.16%   741703364    5.98%  NaN
26  107/08   91055038   22.43%   91917167   -0.94%   646781444    5.80%  NaN
27  107/07   74370924    5.58%   71611190    3.85%   555726406    7.00%  NaN
28  107/06   70438298  -13.01%   84187305  -16.33%   481355482    7.50%  NaN
29  107/05   80968732   -1.10%   72795974   11.23%   410917184   13.02%  NaN
30  107/04   81869781  -21.05%   56871933   43.95%   329948452   13.47%  NaN
31  107/03  103697437   60.42%   85875181   20.75%   248078671    6.06%  NaN
32  107/02   64640562  -18.94%   71422961   -9.50%   144381234   -2.47%  NaN
33  107/01   79740672  -11.30%   76616258    4.08%    79740672    4.08%  NaN
34  106/12   89897252   -3.50%   78112022   15.09%   977447241    3.11%  NaN
35  106/11   93153310   -1.45%   93029912    0.13%   887549989    2.04%  NaN
36  106/10   94519722    6.71%   91085318    3.77%   794396679    2.27%  NaN
37  106/09   88578988   -3.63%   89702807   -1.25%   699876957    2.07%  NaN
38  106/08   91917167   28.36%   94311424   -2.54%   611297969    2.57%  NaN
39  106/07   71611190  -14.94%   76391654   -6.26%   519380802    3.52%  NaN
40  106/06   84187305   15.65%   81390752    3.44%   447769612    5.28%  NaN
41  106/05   72795974   28.00%   73575784   -1.06%   363582307    5.72%  NaN
42  106/04   56871933  -33.77%   66843310  -14.92%   290786333    7.56%  NaN
43  106/03   85875181   20.23%        NaN      NaN   233914400      NaN  NaN
44  106/02   71422961   -6.78%        NaN      NaN   148039219      NaN  NaN
45  106/01   76616258   -1.91%        NaN      NaN    76616258      NaN  NaN
46  105/12   78112022  -16.04%        NaN      NaN   947938344      NaN  NaN
47  105/11   93029912    2.13%        NaN      NaN   869826322      NaN  NaN
48  105/10   91085318    1.54%        NaN      NaN   776796410      NaN  NaN
49  105/09   89702807   -4.89%        NaN      NaN   685711092      NaN  NaN
50  105/08   94311424   23.46%        NaN      NaN   596008285      NaN  NaN
51  105/07   76391654   -6.14%        NaN      NaN   501696861      NaN  NaN
52  105/06   81390752   10.62%        NaN      NaN   425305207      NaN  NaN
53  105/05   73575784   10.07%        NaN      NaN   343914455      NaN  NaN

# 財務比率 獲利能力指標

In [109]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcr/zcr_'+stocknumber+'.djhtm')
df = df[2][0:]
df = df[:15]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
0,獲利能力指標單位：%,獲利能力指標單位：%,獲利能力指標單位：%,獲利能力指標單位：%,獲利能力指標單位：%,獲利能力指標單位：%,獲利能力指標單位：%,獲利能力指標單位：%,獲利能力指標單位：%
1,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
2,種類,合併,合併,合併,合併,合併,合併,合併,合併
3,ROA(C)稅前息前折舊前,8.73,9.04,8.26,7.08,6.88,9.42,8.75,7.87
4,ROA(A)稅後息前,5.1,5.3,4.65,3.05,2.9,4.96,4.46,3.55
5,ROA(B)稅後息前折舊前,7.48,7.8,7.12,5.74,5.83,7.99,7.43,6.46
6,ROE(A)─稅後,7.1,7.23,6.44,4.05,3.59,6.15,5.81,4.67
7,ROE(B)─常續利益,7.09,7.3,6.47,4.03,3.62,6.18,5.87,4.84
8,營業毛利率,51.77,50.2,47.58,43.02,41.31,47.64,47.39,47.84
9,已實現銷貨毛利率,51.76,50.18,47.57,43.04,41.31,47.67,47.39,47.81
10,營業利益率,41.38,39.16,36.82,31.66,29.38,36.97,36.58,36.19
11,稅前淨利率,42.55,40.59,38.33,33.42,31.18,38.33,37.99,37.55
12,稅後淨利率,37.69,36.59,34.5,27.71,28.07,34.51,34.22,30.99
13,業外收支/營收,1.17,1.43,1.52,1.76,1.79,1.37,1.4,1.35
14,常續利益率--稅後,37.66,36.91,34.71,27.56,28.31,34.71,34.57,32.12

# 財務比率 每股比率指標

In [112]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcr/zcr_'+stocknumber+'.djhtm')
df = df[2][0:]
df = df[16:26]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
16,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
17,種類,合併,合併,合併,合併,合併,合併,合併,合併
18,每股淨值(F)(TSE公告數),64.64,62.53,61.2,59.92,67.21,64.67,60.75,57.46
19,常續性EPS,15.5,13.38,12.75,12.3,12.63,13.67,13.61,13.57
20,每股現金流量,7.83,7.83,5.47,4.54,5.89,7.3,3.63,5
21,每股營業額(元),11.98,12.23,11.3,9.29,8.43,11.17,10.04,9
22,每股營業利益(元),4.96,4.79,4.16,2.94,2.48,4.13,3.67,3.26
23,每股稅前淨利(元),5.1,4.97,4.33,3.11,2.63,4.28,3.81,3.38
24,每股綜合損益,4.62,3.83,3.77,2.71,2.55,3.92,3.29,3.53
25,每股盈餘,4.51,4.47,3.9,2.57,2.37,3.86,3.44,2.79

# 財務比率 成長率指標

In [114]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcr/zcr_'+stocknumber+'.djhtm')
df = df[2][0:]
df = df[27:45]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
27,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
28,種類,合併,合併,合併,合併,合併,合併,合併,合併
29,營收成長率,42.02,9.48,12.56,3.31,-11.84,4.4,3.27,9.08
30,營業毛利成長率,77.95,15.36,13.01,-7.09,-27.7,-0.49,-1.98,2.61
31,已實現銷貨毛利成長率,77.93,15.26,13.01,-6.99,-27.63,-0.45,-2,2.6
32,營業利益成長率,99.98,15.98,13.27,-9.62,-33.63,-1.63,-2.87,1.41
33,稅前淨利成長率,93.82,15.93,13.59,-8.04,-31.78,-0.53,-1.61,1.71
34,稅後淨利成長率,90.7,16.07,13.47,-7.63,-31.63,0.7,-0.95,9.09
35,經常淨利成長率,90.7,16.07,13.47,-7.63,-31.63,0.7,-0.95,9.09
36,常續淨利成長率,88.89,16.42,13,-11.39,-30.37,1.61,0.99,14.68
37,總資產成長率,7.13,8.36,8.34,9.05,6.75,4.93,6.98,3.37
38,淨值成長率,-3.81,-3.3,0.74,4.28,8.52,10.16,10.09,11.05
39,總資產報酬成長率,2.13,0.43,0.29,-0.11,-1.12,0.14,-0.06,0.72
40,營收變動率,-2.09,8.26,21.6,10.19,-24.52,11.3,11.6,-5.97
41,營業利益變動率,3.44,15.16,41.39,18.73,-40.01,12.47,12.81,-12.81
42,淨利變動率(單季),0.85,14.81,51.41,8.78,-38.62,12.24,23.25,-19.48
43,稅前盈餘變動率,2.61,14.64,39.47,18.13,-38.62,12.32,12.91,-12.36
44,折舊性FA成長率,29.84,26.15,14.25,10.5,4.95,0.89,-1.62,-4.02

# 財務比率 經營能力指標

In [117]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcr/zcr_'+stocknumber+'.djhtm')
df = df[2][0:]
df = df[46:58]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
46,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
47,種類,合併,合併,合併,合併,合併,合併,合併,合併
48,存貨及應收帳款/淨值,13.4,13.73,15.25,14.43,12.36,13.86,14.9,12.56
49,總資產週轉次數,0.13,0.14,0.13,0.11,0.1,0.14,0.13,0.11
50,應收帳款週轉次,2.17,2.22,2.24,2.16,1.85,2.24,2.39,2.38
51,平均收帳天數,41.92,40.9,40.61,42.08,49.09,40.63,38.05,38.22
52,存貨週轉率(次),1.86,1.76,1.5,1.27,1.21,1.45,1.34,1.32
53,平均售貨天數,48.98,51.74,60.7,71.87,75.12,62.55,67.89,68.89
54,固定資產週轉次數,0.22,0.25,0.25,0.21,0.2,0.27,0.25,0.22
55,淨值週轉率(次),0.19,0.2,0.19,0.15,0.13,0.18,0.17,0.15
56,應付帳款付現天數,24.29,22.22,20.59,19.96,21.99,19.39,20.25,22.32
57,淨營業週期(日),66.61,70.42,80.71,93.99,102.22,83.78,85.69,84.79

# 財務比率 債償能力指標

In [119]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcr/zcr_'+stocknumber+'.djhtm')
df = df[2][0:]
df = df[59:72]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
59,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
60,種類,合併,合併,合併,合併,合併,合併,合併,合併
61,現金流量允當%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,現金再投資%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,流動比率,136.13,139.25,171.68,162.34,262.07,279.46,267.15,207.14
64,速動比率,120.11,122.44,147.62,141.79,229.21,242.1,228.1,181.49
65,總負債/總淨值,39.73,39.62,34.44,44.06,25.46,24.6,25.01,37.75
66,負債比率％,28.43,28.38,25.62,30.59,20.29,19.74,20,27.41
67,淨值/資產,71.57,71.62,74.38,69.41,79.71,80.26,80,72.59
68,長期資金適合率(A),119.84,121.8,134.61,139.1,160.59,161.78,155.72,152.19
69,借款依存度,12.02,10.81,8.97,10.4,9.18,10.76,10.52,8.73
70,或有負債/淨值,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,利息保障倍數,250.07,201.1,134.19,94.14,76.84,127.82,134.81,140.41

# 財務比率 成本費用率指標

In [121]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcr/zcr_'+stocknumber+'.djhtm')
df = df[2][0:]
df = df[73:84]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
73,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
74,種類,合併,合併,合併,合併,合併,合併,合併,合併
75,員工人數,48752,48752,48752,48752,48752,48752,48602,48602
76,營業費用率,10.41,11.01,10.71,11.27,11.9,10.65,10.8,11.33
77,用人費用率,10.47,10.11,10.11,10.21,10.82,9.88,10.54,10.75
78,研究發展費用率,8.04,8.08,8.18,8.88,9.34,8.18,8.41,8.53
79,呆帳費用率,0,0,0,0,0,0,0,0
80,現金流量比率,34.44,34.36,28.65,18.92,40.36,55.61,29.25,28.03
81,有息負債利率,0.27,0.37,0.49,0.48,0.52,0.53,0.42,0.34
82,稅率(A),11.41,9.86,10,17.1,9.97,9.97,9.91,17.46
83,稅率(B)%,11.41,9.86,10,17.1,9.97,9.97,9.91,17.46

# 財務比率 其他

In [152]:
import pandas as pd
stocknumber="2330"

df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcr/zcr_'+stocknumber+'.djhtm')
df = df[2][0:]
df = df[85:90]
#df.columns = df.iloc[0]
df

,0,1,2,3,4,5,6,7,8
85,期別,2020.1Q,2019.4Q,2019.3Q,2019.2Q,2019.1Q,2018.4Q,2018.3Q,2018.2Q
86,種類,合併,合併,合併,合併,合併,合併,合併,合併
87,每人營收,6371,6507,6011,4943,4486,5944,5357,4800
88,每人營業利益,2636,2548,2213,1565,1318,2197,1960,1737
89,每人配備率,29501,27740,24572,23443,22720,21990,21574,21280

In [142]:
df_T=df.T
df_T

        85  86    87      88     89
0       期別  種類  每人營收  每人營業利益  每人配備率
1  2020.1Q  合併  6371    2636  29501
2  2019.4Q  合併  6507    2548  27740
3  2019.3Q  合併  6011    2213  24572
4  2019.2Q  合併  4943    1565  23443
5  2019.1Q  合併  4486    1318  22720
6  2018.4Q  合併  5944    2197  21990
7  2018.3Q  合併  5357    1960  21574
8  2018.2Q  合併  4800    1737  21280

In [143]:
x = df_T.values.tolist()[0]
x

['期別', '種類', '每人營收', '每人營業利益', '每人配備率']